version: "3.3"

services:

    drawio:
        image: jgraph/drawio
        container_name: draw
        stdin_open: true
        tty: true
        restart: unless-stopped
        ports:
            - "8200:8080"
            - "8243:8443"
            